logging:
  level:
    org:
      mongodb:
        driver: ERROR
      springframework:
        boot:
          web:
            embedded:
              netty: DEBUG
        http:
          server:
            reactive:
              ReactorHttpHandlerAdapter: DEBUG
    reactor:
      ipc:
        netty:
          http: DEBUG

server:
  port: 8081