FROM openjdk:8-jre-alpine
COPY ./target/spring-boot-blocking-1.0.0-SNAPSHOT.jar /usr/src/spring-boot-blocking/
WORKDIR /usr/src/spring-boot-blocking
CMD ["java", "-jar", "spring-boot-blocking-1.0.0-SNAPSHOT.jar"]