FROM openjdk:8-jre-alpine
COPY ./target/spring-boot-reactive-0.0.1-SNAPSHOT.jar /usr/src/spring-boot-reactive/
WORKDIR /usr/src/spring-boot-reactive
CMD ["java", "-jar", "spring-boot-reactive-0.0.1-SNAPSHOT.jar"]